language: python
python:
  - '3.6'

install:
  - pip install pipenv
  - pipenv --python ${TRAVIS_PYTHON_VERSION}
  - pipenv sync --dev

script:
  - pipenv check
  - pipenv run python -m unittest discover -s tests
